server:
  port: 9091
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9004/eureka/
spring:
  application:
    name: feign_consumer
feign:
  hystrix:
    enabled: true