server:
  port: 9005
spring:
  application:
    name: DEPTSERVICEPROVIDER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9004/eureka/
  instance:
    prefer-ip-address: true
    instance-id: DEPTSERVICEPROVIDER-hystrix-9005
info:
  app.name: dept-service-hystrix-9005
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$