server:
  port: 8003

spring:
  application:
    name: DEPTSERVICEPROVIDER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9004/eureka/
  instance:
    prefer-ip-address: true
