server:
  port: 5001

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9004/eureka/
  instance:
    prefer-ip-address: true
    instance-id: zuul-5001
info:
  app.name: zuul-gateway
  company.name: www.oocl.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  ignored-services: "*"
#  prefix: /consumer
  routes:
    mydept.serviceId: DEPTSERVICEPROVIDER
    mydept.path: /mydept/**