server:
  port: 9001
eureka:
  instance:
    hostname: eureka9001.com
  client:
    register-with-eureka: false # false 标识不向注册公司注册自己
    fetch-registry: false  # false 标识自己及时注册中心，我的职责就是维护服务实例。并不需要检索服务
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 设置与eureka server交互的地址查询服务和注册服务
      defaultZone: http://eureka9002.com:9002/eureka/,http://eureka9004.com:9004/eureka/